# Generated by Django 2.2.1 on 2019-07-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190713_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='pma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=90)),
                ('merchant_key', models.CharField(max_length=100)),
            ],
        ),
    ]
